[tools]
"pipx:ansible-core" = "2.18"
age = "latest"
op = "latest"
sops = "latest"
talhelper = "latest"
talosctl = "latest"
terraform = "latest"

[tasks.tf]
description = "Run Terraform with secrets loaded from 1Password"
dir = "terraform"
run = "op run --env-file=.env -- terraform"
